version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: America/New_York
    groups:
      development-tooling:
        dependency-type: development
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "12:30"
      timezone: America/New_York
    open-pull-requests-limit: 5
